#!/usr/bin/with-contenv sh

#set -x

source /etc/colors.sh

PREFFIX="[services.d] [rclone-webdav]-$(s6-basename ${0}):"

SERVICE_DIR=/var/run/s6/services
SERVICE=rclone-webdav

# Check if the rclone process with the given remote path is running
checkRclone(){
    ps aux | grep '.rclon[e].*'$RemotePath'' | grep -v grep > /dev/null
    return $?
}

# Kill the rclone-webdav service if it's running
if checkRclone; then
    s6-svc -d ${SERVICE_DIR}/${SERVICE}
    tempPID="$(pgrep rclon[e])"
    kill ${tempPID}
else
    echo -e "${PREFFIX} ${Red}rclone process not present, restarting container[ERROR]${Color_Off}"
    s6-svscanctl -t /var/run/s6/services
fi

# Check if the rclone service is running and wait till it's stopped
echo -e "${PREFFIX} ${Yellow}waiting for rclone shutdown${Color_Off}"
while checkRclone -eq 0; do
    sleep 0.1
done
