version: "3.5"
services:
  jellyfin_rclone:
    image: coolimc/jellyfin-rclone
    container_name: jellyfin_rclone
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - /path/to/rclone_config:/rconfig
      - /path/to/jellyfin_config:/config
      - /path/to/tvseries:/data/tvshows #optional
      - /path/to/movies:/data/movies #optional
      - /opt/vc/lib:/opt/vc/lib #optional
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    environment:
      - RemotePath=mediaefs:/
      - MountPoint=/mnt/mediaefs
      - ConfigDir=/rconfig
      - ConfigName=rclone.conf
      - MountCommands=--allow-other --allow-non-empty #optional
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=<022> #optional
      - JELLYFIN_PublishedServerUrl=192.168.2.1 #optional
    devices:
      # FUSE Device
      - /dev/fuse
      # GPU Devices
      - /dev/dri:/dev/dri #optional
      - /dev/vcsm:/dev/vcsm #optional
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped